### ISSUE TITLE
Kod asm

### ISSUE THREAD

**Issue by kubasikora** [EiTI-18L-TMLab/Lab3#1]
Proszę o push tego co już jest, przyda się do wejściówki

**Comment by kubasikora** [comment]
Bitte

**Comment by stratixx** [comment]
@kubasikora  wrzuciłem, sprawdź co możesz

**Comment by stratixx** [comment]
asm.s43 polecam i pozdrawiam odważnych xd

**Comment by kubasikora** [comment]
Dziekuje, zamykam
